name: Android CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 如果有签名需求，可以在这里配置，这里默认构建 Debug 版或常规 Release
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/artifacts/upload-artifact@v4
      with:
        name: android-app-release
        path: app/build/outputs/apk/release/*.apk
